export const FRANCHISES = [
  { key: "marvel-cinematic-universe", label: "Marvel Cinematic Universe" },
  { key: "x-men-universe", label: "X-Men Universe" },
  { key: "star-wars", label: "Star Wars" },
  { key: "lord-of-the-rings", label: "Lord of the Rings" },
  { key: "james-bond", label: "James Bond" },
  { key: "conjuring-universe", label: "Conjuring Universe" },
  { key: "transformers", label: "Transformers" },
  { key: "fast-and-furious", label: "Fast & Furious" },
  { key: "dc-extended-universe", label: "DC Extended Universe" },
  { key: "monsterverse", label: "MonsterVerse" },
  { key: "wizarding-world", label: "Wizarding World" },
  { key: "maze-runner", label: "Maze Runner" },
  { key: "hunger-games", label: "Hunger Games" },
  { key: "divergent", label: "Divergent" },
  { key: "evil-dead", label: "Evil Dead" },
  { key: "john-wick", label: "John Wick" },
  { key: "planet-of-the-apes", label: "Planet of the Apes" },
];
